# Generated by Django 4.2.30 on 2026-10-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotation_documents/')),
                ('document_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOCX', 'Word Document'), ('EXCEL', 'Excel Workbook')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='quotations.quotation')),
            ],
        ),
    ]
